# -*- coding: utf-8 -*-
"""
Claude CLI Installation Script Generator
"""

from typing import List, Dict
from pathlib import Path
from devpal.core.i18n import Locale, get_i18n_context


class InstallScriptGenerator:
    """Generate Claude CLI installation scripts with i18n support"""

    def __init__(self, locales: List[Locale] = None):
        """Initialize generator with supported locales"""
        self.locales = locales or [Locale.EN, Locale.ZH]
        self.i18n_contexts = {
            locale: get_i18n_context(locale) for locale in self.locales
        }

    def _collect_messages(self) -> Dict[str, Dict[str, str]]:
        """Collect all installation messages for all locales"""
        message_keys = [
            'install.welcome', 'install.checking_node', 'install.node_found',
            'install.node_not_found', 'install.checking_npm', 'install.npm_found',
            'install.npm_missing', 'install.installing', 'install.install_success',
            'install.install_failed', 'install.verifying', 'install.verify_success',
            'install.verify_failed', 'install.done', 'install.manual_install',
            'install.already_installed',
        ]

        messages_by_locale = {}
        for locale in self.locales:
            ctx = self.i18n_contexts[locale]
            messages_by_locale[locale.value] = {key: ctx.t(key) for key in message_keys}

        return messages_by_locale

    def generate_bash_script(self) -> str:
        """Generate Bash installation script"""
        messages = self._collect_messages()

        # Build message function
        msg_cases = []
        for locale, msgs in messages.items():
            cases = []
            for key, value in msgs.items():
                escaped = value.replace("'", "'\\''")
                cases.append(f"            {key}) echo '{escaped}' ;;")

            locale_case = f"        {locale})\n            case \"$1\" in\n"
            locale_case += "\n".join(cases)
            locale_case += "\n                *) echo \"$1\" ;;\n            esac\n            ;;"
            msg_cases.append(locale_case)

        msg_function = "msg() {\n    local key=\"$1\"\n    case \"$SCRIPT_LANG\" in\n"
        msg_function += "\n".join(msg_cases)
        msg_function += "\n        *) echo \"$1\" ;;\n    esac\n}"

        script = f'''#!/usr/bin/env bash
# Claude Code CLI Installation Script
# Generated by DevPalAgent

set -euo pipefail

SCRIPT_LANG="en"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
NC='\\033[0m'

# Detect language
for arg in "$@"; do
    case "$arg" in
        --lang=*) SCRIPT_LANG="${{arg#*=}}" ;;
    esac
done

{msg_function}

command_exists() {{
    command -v "$1" >/dev/null 2>&1
}}

check_node() {{
    echo "$(msg 'install.checking_node')"
    if command_exists node; then
        echo -e "${{GREEN}}✓${{NC}} Node.js found"
        return 0
    else
        echo -e "${{RED}}✗${{NC}} $(msg 'install.node_not_found')"
        return 1
    fi
}}

check_npm() {{
    echo "$(msg 'install.checking_npm')"
    if command_exists npm; then
        echo -e "${{GREEN}}✓${{NC}} npm found"
        return 0
    else
        echo -e "${{RED}}✗${{NC}} $(msg 'install.npm_missing')"
        return 1
    fi
}}

install_claude_cli() {{
    echo "$(msg 'install.installing')"
    if npm install -g @anthropic-ai/claude-code; then
        echo -e "${{GREEN}}✓${{NC}} $(msg 'install.install_success')"
        return 0
    else
        echo -e "${{RED}}✗${{NC}} Installation failed"
        return 1
    fi
}}

verify_installation() {{
    echo "$(msg 'install.verifying')"
    if command_exists claude; then
        echo -e "${{GREEN}}✓${{NC}} $(msg 'install.verify_success')"
        return 0
    else
        echo -e "${{RED}}✗${{NC}} $(msg 'install.verify_failed')"
        return 1
    fi
}}

main() {{
    echo "$(msg 'install.welcome')"
    echo ""

    if command_exists claude; then
        version="$(claude --version 2>/dev/null || echo 'unknown')"
        already_installed="$(msg 'install.already_installed')"
        already_installed="${{already_installed//{{version}}/$version}}"
        echo -e "${{GREEN}}✓${{NC}} $already_installed"
        echo "$(msg 'install.done')"
        exit 0
    fi

    if ! check_node; then
        echo "$(msg 'install.manual_install')"
        exit 1
    fi

    if ! check_npm; then
        echo "$(msg 'install.manual_install')"
        exit 1
    fi

    echo ""
    if ! install_claude_cli; then
        exit 1
    fi

    echo ""
    if ! verify_installation; then
        exit 1
    fi

    echo ""
    echo "$(msg 'install.done')"
}}

main "$@"
'''
        return script

    def generate_batch_script(self) -> str:
        """Generate Windows Batch installation script"""
        return "@echo off\\necho Batch installer\\n"

    def generate_python_script(self) -> str:
        """Generate Python cross-platform installation script"""
        return "#!/usr/bin/env python3\\nprint('Python installer')\\n"

    def generate_all(self, output_dir: Path) -> List[Path]:
        """Generate all installation scripts"""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        generated_files = []

        bash_path = output_dir / 'install_claude_cli.sh'
        bash_path.write_text(self.generate_bash_script(), encoding='utf-8')
        bash_path.chmod(0o755)
        generated_files.append(bash_path)

        batch_path = output_dir / 'install_claude_cli.bat'
        batch_path.write_text(self.generate_batch_script(), encoding='utf-8')
        generated_files.append(batch_path)

        python_path = output_dir / 'install_claude_cli.py'
        python_path.write_text(self.generate_python_script(), encoding='utf-8')
        python_path.chmod(0o755)
        generated_files.append(python_path)

        return generated_files
