# -*- coding: utf-8 -*-
"""
Python language plugin for DevPalAgent
"""

from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from .base import DependencyInfo, FileAnalysisResult, LanguagePlugin, SymbolInfo


class PythonLanguagePlugin(LanguagePlugin):
    """Python language plugin"""

    def get_language_id(self) -> str:
        return "python"

    def get_language_name(self) -> str:
        return "Python"

    def get_supported_extensions(self) -> List[str]:
        return [".py", ".pyi", ".pyw"]

    def get_build_command(self) -> List[str]:
        """Python doesn't require compilation"""
        return []

    def get_test_command(self) -> List[str]:
        """Return pytest command"""
        return ["pytest", "-v", "--tb=short"]

    def get_file_structure(self) -> Dict[str, str]:
        """Python project standard structure"""
        return {
            "src": "Source code directory",
            "tests": "Test directory",
            "docs": "Documentation directory",
            "data": "Data files directory",
            ".spec": "OpenSpec artifacts",
        }

    def get_package_manager(self) -> str:
        return "pip"

    def get_config_file(self) -> str:
        return "pyproject.toml"

    def get_test_framework(self) -> str:
        return "pytest"

    def get_dependency_file(self) -> str:
        return "requirements.txt"

    def validate_syntax(self, code: str) -> bool:
        """Validate Python syntax"""
        try:
            compile(code, "<string>", "exec")
            return True
        except SyntaxError:
            return False

    def get_default_imports(self) -> List[str]:
        """Get common Python imports"""
        return [
            "from typing import List, Dict, Optional, Any",
            "from pathlib import Path",
            "import sys",
            "import os",
        ]

    def get_test_template(self) -> str:
        """Get pytest test template"""
        return '''# -*- coding: utf-8 -*-
"""
Test module for {module_name}
"""

import pytest
from {module_name} import *


class Test{ClassName}:
    """Test class for {ClassName}"""

    def test_example(self):
        """Example test case"""
        assert True
'''

    def get_main_template(self) -> str:
        """Get Python main file template"""
        return '''# -*- coding: utf-8 -*-
"""
{project_name} - Main module
"""

import sys
from pathlib import Path

def main():
    """Main entry point"""
    print("Hello from {project_name}!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

    def is_available(self) -> bool:
        """Check if Python is available"""
        import shutil

        return shutil.which("python") is not None or shutil.which("python3") is not None

    def analyze_file(
        self, file_path: Path, options: Optional[Dict[str, Any]] = None
    ) -> FileAnalysisResult:
        """Analyze Python file (basic implementation)"""
        return FileAnalysisResult(
            file_path=file_path,
            language="python",
            success=True,
            symbols=[],
            dependencies=[],
        )

    def get_symbols(self, file_path: Path) -> List[SymbolInfo]:
        """Get symbols from Python file (basic implementation)"""
        return []

    def get_dependencies(self, file_path: Path) -> List[DependencyInfo]:
        """Get dependencies from Python file (basic implementation)"""
        return []

    # ==========================
    # Phase 集成方法（任务 3 实现）
    # ===============================

    def get_required_files_template(self) -> Dict[str, str]:
        """获取必需文件模板（Phase 4 使用）"""
        return {
            "main.py": self.get_main_template(),
            "requirements.txt": "# Python dependencies\n",
            "setup.py": """# -*- coding: utf-8 -*-
from setuptools import setup, find_packages

setup(
    name="{project_name}",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[],
)
""",
            "README.md": "# {project_name}\n\nPython project generated by DevPalAgent.\n",
        }

    def get_test_command(self, project_dir: Optional[Path] = None) -> List[str]:
        """获取测试命令（Phase 10 使用）"""
        if project_dir is None:
            return ["pytest", "-v", "--tb=short"]
        return ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]

    def get_build_command(self, project_dir: Optional[Path] = None) -> List[str]:
        """获取构建命令（Phase 10 使用）"""
        if project_dir is None:
            return []
        return ["python", "-m", "pip", "install", "-e", "."]

    def get_quality_checks(self) -> List[Callable]:
        """获取质量检查函数列表（Phase 9 使用）"""

        def check_main_py(content: str, context: Dict) -> List[Dict[str, Any]]:
            """检查 main.py 是否存在"""
            project_dir = Path(context.get("project_dir", "."))
            main_py = project_dir / "main.py"
            if not main_py.exists():
                return [
                    {
                        "level": "error",
                        "message": "main.py not found",
                        "file": str(main_py),
                    }
                ]
            return []

        def check_requirements_txt(content: str, context: Dict) -> List[Dict[str, Any]]:
            """检查 requirements.txt 是否存在"""
            project_dir = Path(context.get("project_dir", "."))
            req_file = project_dir / "requirements.txt"
            if not req_file.exists():
                return [
                    {
                        "level": "warning",
                        "message": "requirements.txt not found",
                        "file": str(req_file),
                    }
                ]
            return []

        def check_test_files(content: str, context: Dict) -> List[Dict[str, Any]]:
            """检查测试文件是否存在"""
            project_dir = Path(context.get("project_dir", "."))
            tests_dir = project_dir / "tests"
            if not tests_dir.exists():
                return [
                    {
                        "level": "warning",
                        "message": "tests/ directory not found",
                        "file": str(tests_dir),
                    }
                ]
            test_files = list(tests_dir.glob("test_*.py"))
            if not test_files:
                return [
                    {
                        "level": "warning",
                        "message": "No test files found in tests/",
                        "file": str(tests_dir),
                    }
                ]
            return []

        return [check_main_py, check_requirements_txt, check_test_files]

    def get_project_structure(self) -> Dict[str, List[str]]:
        """获取项目目录结构（Phase 2 使用）"""
        return {
            "src": [],
            "tests": [],
            "docs": [],
            "data": [],
        }
